"""Add auth fields to user

Revision ID: 10d6f468f3d8
Revises: ce1290e8dfe3
Create Date: 2026-04-29 19:44:31.289665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10d6f468f3d8'
down_revision = 'ce1290e8dfe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_webhooks')
    op.drop_index('ix_scan_feedback_check_type_feedback', table_name='scan_feedback')
    op.drop_table('scan_feedback')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'role')
    op.drop_column('users', 'company')
    op.drop_column('users', 'name')
    op.drop_column('users', 'hashed_password')
    op.create_table('scan_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('check_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name='scan_feedback_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scan_feedback_pkey')
    )
    op.create_index('ix_scan_feedback_check_type_feedback', 'scan_feedback', ['check_type', 'feedback_type'], unique=False)
    op.create_table('scan_webhooks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('webhook_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('webhook_secret', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('delivered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name='scan_webhooks_scan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scan_webhooks_pkey')
    )
    # ### end Alembic commands ###
