"""Add risk exception models

Revision ID: 1eb96d3489a6
Revises: f001_safe_missing
Create Date: 2026-06-05 00:37:05.806496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb96d3489a6'
down_revision = 'f001_safe_missing'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_exceptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('finding_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_exceptions_domain_id'), 'risk_exceptions', ['domain_id'], unique=False)
    op.create_index(op.f('ix_risk_exceptions_finding_key'), 'risk_exceptions', ['finding_key'], unique=False)
    op.create_table('risk_exception_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exception_id'], ['risk_exceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_exception_history_exception_id'), 'risk_exception_history', ['exception_id'], unique=False)
    op.create_index('idx_report_audit_scan', 'report_audit_logs', ['scan_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_report_audit_logs_scan_id'), 'report_audit_logs', ['scan_id'], unique=False)
    op.create_index(op.f('ix_report_audit_logs_timestamp'), 'report_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_report_audit_logs_viewer_user_id'), 'report_audit_logs', ['viewer_user_id'], unique=False)
    op.drop_constraint('report_share_links_token_key', 'report_share_links', type_='unique')
    op.create_index('idx_report_shares_scan', 'report_share_links', ['scan_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_report_share_links_scan_id'), 'report_share_links', ['scan_id'], unique=False)
    op.create_index(op.f('ix_report_share_links_token'), 'report_share_links', ['token'], unique=True)
    op.create_index(op.f('ix_scans_workspace_id'), 'scans', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'scans', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_index(op.f('ix_scans_workspace_id'), table_name='scans')
    op.drop_index(op.f('ix_report_share_links_token'), table_name='report_share_links')
    op.drop_index(op.f('ix_report_share_links_scan_id'), table_name='report_share_links')
    op.drop_index('idx_report_shares_scan', table_name='report_share_links')
    op.create_unique_constraint('report_share_links_token_key', 'report_share_links', ['token'])
    op.drop_index(op.f('ix_report_audit_logs_viewer_user_id'), table_name='report_audit_logs')
    op.drop_index(op.f('ix_report_audit_logs_timestamp'), table_name='report_audit_logs')
    op.drop_index(op.f('ix_report_audit_logs_scan_id'), table_name='report_audit_logs')
    op.drop_index('idx_report_audit_scan', table_name='report_audit_logs')
    op.drop_index(op.f('ix_risk_exception_history_exception_id'), table_name='risk_exception_history')
    op.drop_table('risk_exception_history')
    op.drop_index(op.f('ix_risk_exceptions_finding_key'), table_name='risk_exceptions')
    op.drop_index(op.f('ix_risk_exceptions_domain_id'), table_name='risk_exceptions')
    op.drop_table('risk_exceptions')
    # ### end Alembic commands ###
