"""add scan schedules table

Revision ID: 2e6380c31bc0
Revises: 003
Create Date: 2026-04-22 17:06:22.633765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e6380c31bc0'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_scan_id', sa.UUID(), nullable=True),
    sa.Column('last_scan_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_scan_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_schedules_domain'), 'scan_schedules', ['domain'], unique=False)
    op.create_index(op.f('ix_scan_schedules_id'), 'scan_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_schedules_id'), table_name='scan_schedules')
    op.drop_index(op.f('ix_scan_schedules_domain'), table_name='scan_schedules')
    op.drop_table('scan_schedules')
    # ### end Alembic commands ###
