"""Add user and domain to scan

Revision ID: c6ba008bc491
Revises: ae4d68329a17
Create Date: 2026-04-29 20:22:57.432281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ba008bc491'
down_revision = 'ae4d68329a17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('domain_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_scans_domain_id'), 'scans', ['domain_id'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.create_foreign_key(None, 'scans', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_domain_id'), table_name='scans')
    op.drop_column('scans', 'domain_id')
    # ### end Alembic commands ###
