"""Add new v3 report fields

Revision ID: ce1290e8dfe3
Revises: 2e6380c31bc0
Create Date: 2026-04-22 22:40:52.333561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce1290e8dfe3'
down_revision = '2e6380c31bc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('email_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('performance_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('tech_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('crawl_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('cve_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'cve_findings')
    op.drop_column('reports', 'crawl_findings')
    op.drop_column('reports', 'tech_findings')
    op.drop_column('reports', 'performance_findings')
    op.drop_column('reports', 'email_findings')
    # ### end Alembic commands ###
